//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper.Bindings {

public enum ADLX_FFX_FRAME_GEN_RATIO {
  FFX_FRAME_GEN_UNKNOWN = 0,
  FFX_FRAME_GEN_2X = 1
}

}
