//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper.Bindings {

public enum ADLX_GFX_IP_VERSION {
  GFX_IP_VERSION_UNKNOWN = 0,
  GFX_IP_VERSION_4,
  GFX_IP_VERSION_5,
  GFX_IP_VERSION_6,
  GFX_IP_VERSION_7,
  GFX_IP_VERSION_8,
  GFX_IP_VERSION_9,
  GFX_IP_VERSION_10_1,
  GFX_IP_VERSION_10_2,
  GFX_IP_VERSION_10_3,
  GFX_IP_VERSION_11_0,
  GFX_IP_VERSION_12_0
}

}
