//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper.Bindings {

public enum ADLX_MGPU_MODE {
  MGPU_NONE = 0,
  MGPU_PRIMARY,
  MGPU_SECONDARY
}

}
