//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper.Bindings {

public enum ADLX_3DLUT_COLORSPACE {
  CS_SRGB = 1,
  CS_BT2020,
  CS_DCIP3,
  CS_NATIVE
}

}
