//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper.Bindings {

public class IADLXGPUMetrics : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPUMetrics(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPUMetrics_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPUMetrics obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPUMetrics obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPUMetrics(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUMetrics_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT TimeStamp(ref int ms) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_TimeStamp(swigCPtr, ref ms);
    return ret;
  }

  public virtual ADLX_RESULT GPUUsage(ref double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUUsage(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUClockSpeed(ref int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUClockSpeed(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUVRAMClockSpeed(ref int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUVRAMClockSpeed(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUTemperature(ref double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUTemperature(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUHotspotTemperature(ref double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUHotspotTemperature(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUPower(ref double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUPower(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUTotalBoardPower(ref double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUTotalBoardPower(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUFanSpeed(ref int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUFanSpeed(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUVRAM(ref int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUVRAM(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUVoltage(ref int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUVoltage(swigCPtr, ref data);
    return ret;
  }

  public virtual ADLX_RESULT GPUIntakeTemperature(ref double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUIntakeTemperature(swigCPtr, ref data);
    return ret;
  }

}

}
