//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper.Bindings {

public class IADLXSystemMetricsSupport : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXSystemMetricsSupport(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXSystemMetricsSupport_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXSystemMetricsSupport obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXSystemMetricsSupport obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXSystemMetricsSupport(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXSystemMetricsSupport_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedCPUUsage(ref bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSystemMetricsSupport_IsSupportedCPUUsage(swigCPtr, ref supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedSystemRAM(ref bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSystemMetricsSupport_IsSupportedSystemRAM(swigCPtr, ref supported);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedSmartShift(ref bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSystemMetricsSupport_IsSupportedSmartShift(swigCPtr, ref supported);
    return ret;
  }

  public virtual ADLX_RESULT GetCPUUsageRange(ref int minValue, ref int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSystemMetricsSupport_GetCPUUsageRange(swigCPtr, ref minValue, ref maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetSystemRAMRange(ref int minValue, ref int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSystemMetricsSupport_GetSystemRAMRange(swigCPtr, ref minValue, ref maxValue);
    return ret;
  }

  public virtual ADLX_RESULT GetSmartShiftRange(ref int minValue, ref int maxValue) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSystemMetricsSupport_GetSmartShiftRange(swigCPtr, ref minValue, ref maxValue);
    return ret;
  }

}

}
